name: Deploy

on:
 push:
   branches:
     - main

jobs:
 deploy:
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Install dependencies
     run: npm install

   - name: Build docs
     run: npm run docs:build

   - name: Deploy to GitHub Pages
     uses: LoLipepe/vuepress@v3
     with:
       github_token: ${{ secrets.GITHUB_TOKEN }}
       publish_dir: ./docs/.vuepress/dist
       branch: gh-pages
